#
# Debug build extras:
# - USB CDC ACM for printk redirection + optional echo
# - USB MSC enabled (host-visible) by default
#

CONFIG_USBD_CDC_ACM_CLASS=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=n

CONFIG_USBD_MSC_CLASS=y
CONFIG_USBD_MSC_LUNS_PER_INSTANCE=1
CONFIG_USBD_MSC_LOG_LEVEL_WRN=y


